/** 主进程 APP 相关通道 */
export const APP = {
  GET_VERSION: 'MAIN_APP__GET_VERSION',
  GET_SYSTEM_INFO: 'MAIN_APP__GET_SYSTEM_INFO',
  OPEN_EXTERNAL_URL: 'MAIN_APP__OPEN_EXTERNAL_URL',
  GET_SYSTEM_MEMORY: 'MAIN_APP__GET_SYSTEM_MEMORY'
} as const;
